### ISSUE TITLE
Multiline output of some operations are formatted differently

### ISSUE THREAD

**Issue by jdow** [jdow/ldap-access-log-humanizer#18]
Given two lines of output like this:
```
Oct 26 13:11:34 slave2.ldap.mdc1.mozilla.com slapd[11086]: conn=6862785 op=75 SRCH base="dc=mozilla" scope=2 deref=3 filter="(&(!(employeeType=disabled))(objectClass=inetOrgPerson)(|(o:dn:=org)(o:dn:=com)(o:dn:=net)(ou:dn:=shared_accounts)))"
Oct 26 13:11:34 slave2.ldap.mdc1.mozilla.com slapd[11086]: conn=6862785 op=75 SRCH attr=mail sshPublicKey pgpFingerprint sn givenName mobile uid uidNumber createTimestamp modifyTimestamp im displayName title description zimbraAlias
```
These are two lines of output for a single operation. The first line lists a few distinct key/value pairs, details about the operation, with each one separated by a space. The second line lists one single detail (the list of attributes), where the values are separated by a space.

So, we need to handle these two lines of output differently in order to achieve something like this:

`{'conn_id': '6862785', 'time': 'Oct 26 13:11:34', 'client': '', 'server': 'slave2.ldap.mdc1.mozilla.com', 'tls': False, 'op_id': 75, 'requests': [{'verb': 'SRCH', 'details': ['base="dc=mozilla"', 'scope=2', 'deref=3', 'filter="(&(!(employeeType=disabled))(objectClass=inetOrgPerson)(|(o:dn:=org)(o:dn:=com)(o:dn:=net)(ou:dn:=shared_accounts)))"', 'attrs=mail,sshPublicKey,pgpFingerprint,sn,givenName,mobile,uid,uidNumber,createTimestamp,modifyTimestamp,im,displayName,title,description,zimbraAlias']}], 'response': {'verb': 'SEARCH RESULT', 'details': ['err=0', 'nentries=100', 'tag=101', 'text='], 'error': 'LDAP_SUCCESS'}}`

**Comment by claudijd** [comment]
I believe this is now fixed in master, with a shim for SRCH, if this is the only example, then we're probably ok.  If there are more, let's put them on the table and code around them or change our tokenization strategy to include parsers as you suggested.
